# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3fd9ae123bd8274ed38fb05bb5a0b93c9b48e353f5b09707b50b9019b5ae0920735bdd63cb8e32a4922e0e57c13500d732382b2444005d4242d944a4b6e524f5

test:
  secret_key_base: 82d5591343b02302020f3083f06f4f9468c60b00d0d0404e276c74a72a4f60550ab2c50b8967640362208d2813df23158ce2adf35e31c21f8cc2fd6ef56f5e6a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
